### ISSUE TITLE
Add Issue Template

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku#108]
Give various fields to show whether the issue is about adding new content or app updates.
And a checkbox to show if the user wanna work on it.
Please comment if any other useful thing can be included.

**Comment by aashutoshrathi** [comment]
I can work on this, just give suggestions, what can be added?

**Comment by anshumanv** [comment]
This issue is about ...

Check for:
* I wanna work on this.
* I ensure that this is not duplicate
* I've gone through the Contributing guidelines

Any other suggestions ?

**Comment by Monal5031** [comment]
Add it in `.github` folder @aashutoshrathi as we did in ChefLib.
Also we can add a point where it confirms that the person has tested its work and that it won't break anything else.

**Comment by aashutoshrathi** [comment]
@Monal5031 Please Check #112 sent 11 minutes ago.

**Comment by anshumanv** [comment]
Yea, need to add a check to make sure he tested his additions in the app and everything's functional.

**Comment by aashutoshrathi** [comment]
@Anshuman-Verma , please suggest on #112 now.
