### ISSUE TITLE
Attack On Titan Opening - Guren No Yumiya 

### ISSUE THREAD

**Issue by DivyeshPuri** [anshumanv/ongaku#109]

**Comment by DivyeshPuri** [comment]
@Anshuman-Verma assign me this issue

**Comment by anshumanv** [comment]
The opening isn't very appealing in itself so make sure you add the anime version which is somewhere around 1:30min and not the full opening :)

**Comment by DivyeshPuri** [comment]
Have a look now @Anshuman-Verma
