### ISSUE TITLE
Some Grammatical errors in Issue and PR Template

### ISSUE THREAD

**Issue by aashutoshrathi** [anshumanv/ongaku#115]
#### This issue is about Error in Issue and PR Templates.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

**Comment by anshumanv** [comment]
Which errors are you referring in particular ?

**Comment by aashutoshrathi** [comment]
@Anshuman-Verma Assign me
