### ISSUE TITLE
UI Enhancement in Info Bar

### ISSUE THREAD

**Issue by DivyeshPuri** [anshumanv/ongaku#117]
#### This issue is about {Anime Name} (OP/ED).

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

**Comment by aashutoshrathi** [comment]
Update First line of Issue Template.

**Comment by anshumanv** [comment]
What is Info bar exactly ?

**Comment by anshumanv** [comment]
You need to explain what enhancement you are opening this issue for.
