### ISSUE TITLE
Add Travis CI Badge to README

### ISSUE THREAD

**Issue by aashutoshrathi** [anshumanv/ongaku#123]
- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

**Comment by aashutoshrathi** [comment]
@Anshuman-Verma only you can add this, I think, so GFI.

**Comment by anshumanv** [comment]
Yea okay
