### ISSUE TITLE
Links not working Naruto Shippuden OST - Ashura-Indra

### ISSUE THREAD

**Issue by DivyeshPuri** [anshumanv/ongaku#133]
#### This issue is about {Naruto Shippuden} (OST).

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [x] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

**Comment by anshumanv** [comment]
Links work perfectly fine for me.
