### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by Monal5031** [anshumanv/ongaku#143]
#### This issue is about updating contributing.md with following points.
```
    - Please solve only one issue per PR.
    - Only one enhancement per PR (more are allowed if the enhancement if very small)
```
- [x] This issue is for enhancement/bug fixing.
- [x] Assign this issue to me.

**Comment by anshumanv** [comment]
Those points can be included, but adding multiple content of a single anime should be allowed as there are way too many ! :octocat:

**Comment by Monal5031** [comment]
@Anshuman-Verma Yeah that seems good, also this point will help in maintaining the history of changes for particular animes.

**Comment by anshumanv** [comment]
Yea right, will be convenient.
