### ISSUE TITLE
Update Image of Fairy Tail(S1) - Sense Of Wonder

### ISSUE THREAD

**Issue by DivyeshPuri** [anshumanv/ongaku#146]
#### This issue is about Fairy Tail (OP/ED/OST).

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [x] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

**Comment by anshumanv** [comment]
Has been fixed in #149
