### ISSUE TITLE
Improvement in Port Section in README

### ISSUE THREAD

**Issue by aashutoshrathi** [anshumanv/ongaku#162]
#### This issue is about Port Section in README.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

**Comment by anshumanv** [comment]
What is the improvement that you're suggesting ?

**Comment by anshumanv** [comment]
@aashutoshrathi ?

**Comment by aashutoshrathi** [comment]
https://github.com/aashutoshrathi/ongaku/tree/readme-port

**Comment by anshumanv** [comment]
Go with it then.
