### ISSUE TITLE
Travis Build Failing Due to some Dead Links

### ISSUE THREAD

**Issue by aashutoshrathi** [anshumanv/ongaku#169]
#### This issue is about Travis Build Failure.

**Dead Links**:
1. http://geodavephotography.com/images/guilty-crown-wallpaper/38061238-guilty-crown-wallpaper.jpg give Error 404.
Guilty Crown ED2 Single - Kokuhaku's Image no longer exist.
2. White Listed mp3fb.com link (not causing failure, but better to change it).

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [x] This issue is a modification to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

**Comment by anshumanv** [comment]
Thanks for bringing that to notice, I was about to ask you to read travis log.
