### ISSUE TITLE
Automated anime songs retrieval

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku#176]
The current setup uses a `data.json` which isn't very robust or reliable, is there a way to automatically get links using some API so we get rid of manually collecting all the links?

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

**Comment by Aystub** [comment]
I don't know of any that already provide this data. But could make one? Dump your data.json into a database like Postgres, use python or something to serve up the data as you need it. Host all of it on Heroku or some other service. Their free tier isn't bad depending on how much traffic your project gets. But if it's huge it'd start costing money regardless of where you host it.

**Comment by Monal5031** [comment]
Accept it @anshumanv django server would work for this 😉 we can create REST API for the data.

**Comment by anshumanv** [comment]
@Aystub thanks for the followup, The problem here is to get rid of data.json completely and use some API that provides links directly of all animes.
@Monal5031 let's do that later if we don't find a workaround.

**Comment by Swardu** [comment]
Using a real database engine such as MariaDB is also an option, which I recommend. MariaDB is great at handling a lot of data, Postgres is mainly for bigger data such as blog post, but works too.

**Comment by anshumanv** [comment]
@GitHugop thanks for the view, perhaps I think the description is not clear, have updated it. Currently we have to aggregate links in data.json, I'm trying to find a method where there is no longer any need to find links and add them in some database or json file, something where we can just get links for all animes in one place.

**Comment by Swardu** [comment]
There are ways, such as using SoundCloud API to search and download music, but it's not a bulletproof method. It's best to have them approved by a human and still allow song requests.

What do you think?

**Comment by anshumanv** [comment]
Right @GitHugop that would be more reliable, in that case I'll probably then set up a database and retrieve links from it. 
Thanks for the follow up anyways @GitHugop
