### ISSUE TITLE
Make page mobile responsive

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku#178]
The current layout ain't mobile responsive and the view is messed up. 

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

**Comment by WEBhicham** [comment]
hi @anshumanv ,

I am interesed in making your amazing anime radio responsie. 
I checked the website on my mobile and it is already pretty mobile friendly. 
are there specific changes you wanna have?

**Comment by anshumanv** [comment]
Hi @WEBhicham !
Thanks for showing interest in this project.
The mobile view is really messed up, perhaps we want to display the full image, make player usable, scale down the icons which are taking too much space.
![screenshot_2017-10-03-23-56-09](https://user-images.githubusercontent.com/21009455/31160364-788d1484-a8ed-11e7-94a7-5f9c337f88d1.png)

**Comment by anshumanv** [comment]
Mobile view is fixed automagically. 🌟
