### ISSUE TITLE
Left side-nav to display playlist

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku#182]
Need a button on the top-left clicking on which will unfold a sidenav which will contain the tracks in sequence to be played, clicking on any particular track will play it.

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/Anshuman-Verma/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

**Comment by vijaygomathinayagam** [comment]
I am a beginner but I will try this

**Comment by anshumanv** [comment]
Sure thing, please go ahead.

**Comment by joseph-perez** [comment]
Hello! I was wondering if this was still being worked on? I forked the repo and pushed some changes for this. Sorry if I'm intruding or anything, I'm new to this haha.

 #187

**Comment by vijaygomathinayagam** [comment]
@joseph-perez please refer pull request #183

**Comment by vijaygomathinayagam** [comment]
@joseph-perez I have done already. Now I'm doing minor changes in it.
