### ISSUE TITLE
Travis issue fails due to invalid link

### ISSUE THREAD

**Issue by Monal5031** [anshumanv/ongaku#186]
#### This issue is about {Anime Name} (OP/ED/OST).

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

The link to image in json file is dead https://github.com/anshumanv/ongaku/blob/master/js/data.json#L1036 here is the link causing the build to fail.

**Comment by anshumanv** [comment]
Thanks for bringing that to notice, I'll fix this ASAP

**Comment by anshumanv** [comment]
Fixed
