### ISSUE TITLE
Migrate all icons to font-awesome

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku#189]
Currently, we're using various images as icons for different functionality. The icons tend to mix up sometimes with the background and aren't clearly visible. I'm thinking of porting all icons while maintaining their positions to use white fa icons with a black border, also on hovering over an icon, it should expand by say 5% or 10% and it should be slight gray filled in that case.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

**Comment by darrylsepeda** [comment]
I'll do this task

**Comment by anshumanv** [comment]
Hey, @darrylsepeda welcome onboard!
Go for it 👍

**Comment by darrylsepeda** [comment]
Thanks @anshumanv 
I have added few icons and make PR, please kindly check.
I tried to replace your play/pause button, but still don't know how because you replace the class using javascript.

I also curious about index.html line 18, there is require jquery, this shows error because require is not defined.. why do u import your jquery like that?

**Comment by darrylsepeda** [comment]
I'll try to help for other tasks tomorrow :)

**Comment by anshumanv** [comment]
Thanks, Changes look great!
About line 18 in which I required jquery since it was needed to run the desktop app https://github.com/anshumanv/ongaku-desktop which was using this repo as a submodule, that no longer persists so I'll remove it, thanks for bringing that to notice.

The icons lack animation and some refinement, could you please check http://openings.moe to get the picture of how to improve it?

**Comment by anshumanv** [comment]
Also, there are some extra files like .idea and some fa cache, please remove them as well.

**Comment by darrylsepeda** [comment]
Already remove .idea folder.. :)
I'll try to look at other things tomorrow

**Comment by anshumanv** [comment]
Sure thing, make sure you get your PR merged before others start sending theirs 😆

**Comment by darrylsepeda** [comment]
please kindly check for the animation

**Comment by anshumanv** [comment]
Animation looks cool as of now, why not make the size to 2x and add some thin black border?
4x takes a lot of screen space 😅

**Comment by darrylsepeda** [comment]
hahaha I make it 4x because I think the previous icon size same as that..
done, 2x with some thin black border

**Comment by anshumanv** [comment]
Thanks so much @darrylsepeda, I really appreciate the help. 😄
