### ISSUE TITLE
Add better tooltiptext

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku#190]
Currently, icons just display the regular HTML tooltips which isn't much appealing, I really like the style of icon tooltips in http://openings.moe, we need something like that.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

**Comment by joseph-perez** [comment]
I can take this one on if that's cool 😄

**Comment by anshumanv** [comment]
It's totally cool @joseph-perez 
Go for it 👍
