### ISSUE TITLE
Improve the current HTML Audio Player UI

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku#192]
The current audio player is very primitive and has poor UI, there are so many better material custom HTML/CSS audio players available out there, we should port to them else the simple player at the top of the screen in http://openings.moe works well too.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

**Comment by darrylsepeda** [comment]
Hi @anshumanv, please kindly check my PR https://github.com/anshumanv/ongaku/pull/211 :)
