### ISSUE TITLE
Add more anime openings, endings, OSTs

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku#195]
Please refer [contributing](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md) to see how to add more content.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This issue is for enhancement/bug fixing.
- [x] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

**Comment by aulisius** [comment]
I would like to take this up!

**Comment by anshumanv** [comment]
Thanks! Trying to make this an unending list. 😄 
Other contributors can also send PR for this issue. 👍

**Comment by saideepd** [comment]
Can I add few more tracks to your awesome playlist ?

**Comment by anshumanv** [comment]
Sure @saideepd, please go ahead. 👍

**Comment by Endless7188** [comment]
I'd like to add a song or two, if that's ok.

**Comment by anshumanv** [comment]
Sure thing @Endless7188, go for it! 👍
