### ISSUE TITLE
Make track name visible on mouse movement

### ISSUE THREAD

**Issue by mohitkyadav** [anshumanv/ongaku#200]
- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [X] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [ ] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

**Comment by anshumanv** [comment]
Can you do it along with #191? Both are related.

**Comment by mohitkyadav** [comment]
It's up to you, @anshumanv .

**Comment by anshumanv** [comment]
Okay lol.

**Comment by surmistry** [comment]
Hi @anshumanv mind if I check this out?

**Comment by anshumanv** [comment]
Sure thing @surmistry, go for it. 👍

**Comment by anshumanv** [comment]
I just tried and it looks annoying @mohitkyadav, whenever you wanna seek track or set preferences it doesn't look good for track name to popup again and again. If the user wanna know the track name there's always the playlist where they can look in.
@surmistry thanks for showing interest in this, but please take up some other issue or open if you think there are enhancements possible.

**Comment by darrylsepeda** [comment]
@anshumanv I tried my best to make it looks good, by showing the track name if user hover to the player timeline. If u don't agree with it or have other opinion, please let me know. I'll fix as soon as possible.

**Comment by anshumanv** [comment]
@darrylsepeda thanks for the PR but let's leave this one. I asked some of the users and they aren't very happy about it. Please add commits in #211

**Comment by darrylsepeda** [comment]
okay @anshumanv

**Comment by anshumanv** [comment]
Thanks for understanding. 😄
