### ISSUE TITLE
Side bar to close when user click out of side bar.

### ISSUE THREAD

**Issue by ong-yy** [anshumanv/ongaku#205]
The side bar should close whenever user click anywhere but the side bar.
The close button to side bar is only available on top of the side bar. If user navigate or scroll to the bottom, the side bar can't be close except going back to the top and close it.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

**Comment by anshumanv** [comment]
Hey @YernYee thanks for this, in fact, I was gonna open an issue for the same. Are you up for this?

**Comment by darrylsepeda** [comment]
Can u put hacktoberfest label for this enhancement?
I've added the functionality plus escape button to close the sidebar
