### ISSUE TITLE
Need a small search bar on playlist to filter tracks

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku#208]
The track playlist that slides in from the left has no option to filter out tracks with name, we can add a small text field to the left of the close button which will filter songs in which the entered string is present.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

**Comment by hisivasankar** [comment]
May I work on this?

**Comment by anshumanv** [comment]
Go for it @hisivasankar 👍

**Comment by hisivasankar** [comment]
Thanks 👍

**Comment by hisivasankar** [comment]
@anshumanv, could you please assign it to my name? Also could you please add `in progress` label?
