### ISSUE TITLE
Design a logo for the repo

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku#214]
Since the repo is quite popular now, we need to have a nice logo for this! 😄 
I'm a big fan of material design, it would be great if we can get a real sweet material designed logo for the repo.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

**Comment by devmattrick** [comment]
I may be able to help out. Do you have any ideas for what to make it look like?

**Comment by anshumanv** [comment]
@devmattrick thanks for considering a contribution here! 😄 
I have no preferences for the logo (do what looks good to you), even if you write a nice materially designed 'ongaku' then it would be fine.

**Comment by 123survesh** [comment]
![animradiologo](https://user-images.githubusercontent.com/8644987/31869352-00b8716a-b7c5-11e7-987e-68cd00442218.jpg)
Hi I have tried a logo for the Anime Radio, do check it out

**Comment by anshumanv** [comment]
Doesn't look that good @123survesh, I think we need a simple Ongaku written in some good styling.

**Comment by 123survesh** [comment]
Oh ok

**Comment by 123survesh** [comment]
What do you think about this one?
![ongaku](https://user-images.githubusercontent.com/8644987/32067603-6c624c9a-baa1-11e7-9c6d-095ad43dd5a8.jpeg)

**Comment by anshumanv** [comment]
@123survesh thanks for your effort, but this one's complicated.
Probably can you create something with a nice material colored `O` with a music note icon inside it?

**Comment by thedavidzhao** [comment]
Something like this?

![ongaku logo-01](https://user-images.githubusercontent.com/23362199/32092988-aa52b7f2-bac8-11e7-9ae0-b20d4c29b976.png)

**Comment by anshumanv** [comment]
@thedavidzhao looks nice, can you perhaps make an outline of `O` and put in a filled music symbol, essentially reverse everything.

**Comment by 123survesh** [comment]
@thedavidzhao It looks cool, what software do you use to create this?

**Comment by thedavidzhao** [comment]
@anshumanv something more like this?

![ongaku logo-02-01](https://user-images.githubusercontent.com/23362199/32205338-09b2820a-bdc5-11e7-8ea6-455b384bdd9a.png)

@123survesh Adobe Illustrator

**Comment by anshumanv** [comment]
Woah @thedavidzhao looks awesome! :+1: :smile:

**Comment by thedavidzhao** [comment]
@anshumanv I've created PR #237, not entirely sure if I have the right logo location or PR text body
