### ISSUE TITLE
Remove the close button on tracklist and fixed search on top

### ISSUE THREAD

**Issue by ong-yy** [anshumanv/ongaku#217]
To remove the close button on tracklist because we can just click outside to close it now and the close button isn't even fixed on top to close anytime. 
Fixed search input on top so that you can search anywhere on tracklist.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

**Comment by anshumanv** [comment]
Sounds good, go for it @YernYee! 👍

**Comment by anshumanv** [comment]
I think we should leave the close button as it is, but when the user scrolls down we should fix the search bar on top.

**Comment by ong-yy** [comment]
@anshumanv, here is a PR #218 that removed close button and fix search bar on top. 
I'll branch and make another one without removing close button later.
