### ISSUE TITLE
Improve site performance

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku#225]
The website has now reached a stable set of features, all that remains is optimizing the performance of the website, I just recently checked and it was quite poor - https://developers.google.com/speed/pagespeed/insights/?url=ongaku.js.org&tab=mobile

It describes on how someone can improve the performance, please check it once.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

**Comment by norech** [comment]
I'm on it. I will try to optimize 😃

**Comment by anshumanv** [comment]
Hey, @Norech good to have you onboard! 😄 
Thanks 👍

**Comment by norech** [comment]
I optimized the loading order and the loading time is 2 times faster:
```
	| STATE                    | ORIGINAL | OPTIMIZED |
        |--------------------------|----------|-----------|
	| First Paint              | 2,650 ms |  1,760 ms |
	| First Interactive        | 4,920 ms |  2,100 ms |
	| Consistently Interactive | 4,920 ms |  2,100 ms |
```

From Chrome Audits:
![image](https://user-images.githubusercontent.com/32593294/31953654-90185fb6-b8f4-11e7-82a3-135cd83f28be.png)

**Comment by anshumanv** [comment]
Thanks for the statistics, it's really easy for me this way! 😄

**Comment by starkblaze01** [comment]
Hey, @Norech I just checked the performance again here - https://developers.google.com/speed/pagespeed/insights/?url=ongaku.js.org&tab=mobile
and saw no improvement, are you sure this is the most optimized state?

**Comment by norech** [comment]
It's wierd. I will see what I can improve.

**Comment by norech** [comment]
The wierdest thing I found is that Google Pagespeed consider non-blocking scripts as blocking scripts.
