### ISSUE TITLE
Save song as favourite

### ISSUE THREAD

**Issue by SoldierCorp** [anshumanv/ongaku#233]
#### 

What do you think if we implement a feature to save a song as favourite? Having another list that will show the favourite ones or even in the same list but with a button to filter the favourites.

- [ ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [ ] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

**Comment by anshumanv** [comment]
This has been on my mind for a while, I was thinking of implementing a login feature where users can login and maintain their playlist they wanna hear.
Else we can use browserstorage to store the list of favourites and we can have a nice ⭐️ button which will display only the `starred` songs.
What do you think can be implemented easily?

**Comment by SoldierCorp** [comment]
I was thinking to implement the same thing with browser storage, local storage or cookies, etc. no logging needed... just something simple.

I will start the implementation tonight and I will let you know the progress tomorrow at night or at noon.

**Comment by anshumanv** [comment]
Alright, thanks so much! 😄

**Comment by OuKevin** [comment]
is anyone looking into this? I can try something out.

**Comment by OuKevin** [comment]
Added a PR #238
