### ISSUE TITLE
Fix Travis Failure

### ISSUE THREAD

**Issue by aashutoshrathi** [anshumanv/ongaku#239]
#### This issue is about Travis Failure.
We need to change all www.youtubeinmp3.com links as service is no more available.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [ ] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

**Comment by anshumanv** [comment]
Quick!

**Comment by aashutoshrathi** [comment]
@anshumanv fix this one ASAP, I have PR for #240 ready.

**Comment by aashutoshrathi** [comment]
Either remove these links or fix them
```
Issues :-( > Links 
1. [L0106] http://yt-files.com/yt-dd.php?id=0m-JsMXxXsQ&hash=1163f36946da6ba620dc63dc93d86069&name=Haikyuu Connection refused - connect(2) for "yt-files.com" port 80 
2. [L0112] http://yt-files.com/yt-dd.php?id=xP5_SnR75ZU&hash=81f36d506e80f82f1bf2eab97aab858a&name=Haikyuu!! Connection refused - connect(2) for "yt-files.com" port 80 
3. [L0382] http://yt-files.com/yt-dd.php?id=x8CfQ3P-Z9w&hash=1c2320258ccb4b548daa83d0cbc1ec79&name=Naruto%20Shippuden%20Opening%2018 Connection refused - connect(2) for "yt-files.com" port 80 
4. [L0388] http://yt-files.com/yt-dd.php?id=ZrBqxZ1T_5M&hash=67bfefcf768c91f02605582066ed83dc&name=Naruto%20Shippuden%20Opening%2019%20-%20Blood%20Circulator%20(Extended%20Version Connection refused - connect(2) for "yt-files.com" port 80 
5. [L0490] http://yt2converter.com/yt-dd.php?id=tHG6pXGxxIE&hash=661a2d713365fe1720bd581dbb2a4596&t=6&name=Dragon%20Ball%20Super%20Opening%20#2 getaddrinfo: Name or service not known 
6. [L0526] http://yt-files.com/yt-dd.php?id=m4O2VS4511Y&hash=29f2d27354eb0d248618a2b398d85904&name=Shingeki%20no%20Kyojin%20Attack%20on%20Titan%20Opening%20OP%20Guren%20no%20Yumiya%20Linked%20Horizon%20Extended%20Ver Connection refused - connect(2) for "yt-files.com" port 80 
7. [L0621] https://www.youtubeinmp3.com/fetch/?video=https://www.youtube.com/watch?v=n-or12ftZB8 getaddrinfo: Name or service not known 
8. [L1250] http://www.youtubeinmp3.com/fetch/?video=https://www.youtube.com/watch?v=IK1K9O3y-gk getaddrinfo: Name or service not known
```

**Comment by anshumanv** [comment]
I have asked @starkblaze01 to complete this.

**Comment by starkblaze01** [comment]
Fixed Travis failure for these lines:-
L 0106, L 0112, L 0382, L 0388, L 0490, L 0526, L 0621, L 1250
and also fixed Travis Failure for a few Naruto Shippuden OSTs

**Comment by anshumanv** [comment]
The only @starkblaze01 :raised_hands:

**Comment by aashutoshrathi** [comment]
There is 404 on nearly 56 URIs merged yesterday 😢

**Comment by aashutoshrathi** [comment]
There is 404 on nearly 56 URIs merged yesterday 😢

**Comment by aashutoshrathi** [comment]
Please change every `66.90.93.122/ost/` in repository to `66.90.93.122/anime_ost/`.
@starkblaze01 one more PR will be appreciated. 🙏

**Comment by aashutoshrathi** [comment]
Please change every `66.90.93.122/ost/` in repository to `67.159.62.2/anime_ost/`.
@starkblaze01 one more PR will be appreciated and refer to this issue in PR. 🙏 
cc: @anshumanv

**Comment by starkblaze01** [comment]
Fixed Travis Failure
