### ISSUE TITLE
Display track name

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku#24]
The name of the track needs to show up when a new track is loaded.

**Comment by Monal5031** [comment]
Can I work on this 😛

**Comment by anshumanv** [comment]
Yes please, make sure the heading displays then fades away and somewhere above the seek-bar this would look good. And dont add any extra content as u did in crazy-canvas :stuck_out_tongue:

**Comment by Monal5031** [comment]
Okay sure, just some nice and simple heading, nothing as in `crazy-canvas` not `carzy-canvas` 😜

**Comment by anshumanv** [comment]
PS : I've already stored the name of each track in data.json, easy pick.
