### ISSUE TITLE
Auto deploy to 'surge' on every pull request

### ISSUE THREAD

**Issue by aashutoshrathi** [anshumanv/ongaku#240]
#### This issue is about Auto Deployment feature.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This issue is for adding feature.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

**Comment by anshumanv** [comment]
We need something that will comment the surge deployed link on the PR.
Right?

**Comment by aashutoshrathi** [comment]
No, it will be like, as soon as Travis Build completes, our PR Template will contain a demo link as
`ongaku-js-{PR-NUM}.surge.sh`
and this link will be active if the build is successful.

**Comment by aashutoshrathi** [comment]
Check this https://github.com/aashutoshrathi/ongaku/pull/1

**Comment by anshumanv** [comment]
I'll do it tomorrow ASAP.

**Comment by anshumanv** [comment]
There are some major problems going on with links, the hylia apparently is porting their servers. This will need to wait.
Btw some good use of *susper* :wink:
