### ISSUE TITLE
Populate and display the list of tracks in sequence.

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku#25]
Probably a button that unfolds the populated list will look well.

**Comment by Monal5031** [comment]
Will do this one too 😄 assign it please.

**Comment by anshumanv** [comment]
@Monal5031 you can have it.

**Comment by Monal5031** [comment]
@Anshuman-Verma Please assign this one to me n @aashutoshrathi 
@aashutoshrathi lets work it out today.

**Comment by anshumanv** [comment]
This gh assigning bug still persists, anyways discuss with @aashutoshrathi and do the appropriate.
