### ISSUE TITLE
Player is not working

### ISSUE THREAD

**Issue by SoldierCorp** [anshumanv/ongaku#252]
![image](https://user-images.githubusercontent.com/1775881/33565257-45071b3a-d8e2-11e7-9663-11ce71f20cc9.png)

#### This issue is about {Anime Name} (OP/ED/OST).

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [ ] Assign this issue to me.

**Comment by anshumanv** [comment]
Thanks so much @SoldierCorp for bringing that to notice, I'll look into it soon.
