### ISSUE TITLE
JSON standards not being followed

### ISSUE THREAD

**Issue by DipanshKhandelwal** [anshumanv/ongaku#261]
JSON file is not following standards.

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [ ] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

**Comment by anshumanv** [comment]
Closing this since we will get rid of JSON soon. Thanks for the heads up though. :+1:
