### ISSUE TITLE
Tokyo Ghoul Image Link

### ISSUE THREAD

**Issue by DivyeshPuri** [anshumanv/ongaku#262]
#### This issue is about {Anime Name} (OP/ED/OST).

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [x] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

**Comment by anshumanv** [comment]
Make sure you add same image from a different source.
