### ISSUE TITLE
Updating Image Source of Code Geass (Hangyaku no Lelouch) ED1

### ISSUE THREAD

**Issue by DivyeshPuri** [anshumanv/ongaku#264]
#### This issue is about {Anime Name} (OP/ED/OST).

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This issue is for enhancement/bug fixing.
- [x] This issue is an addition to JSON database.
- [x] I have gone through [Contribution Guidelines](https://github.com/anshumanv/ongaku/blob/master/CONTRIBUTING.md).
- [x] Assign this issue to me.

**Comment by anshumanv** [comment]
Is it not loading?

**Comment by DivyeshPuri** [comment]
It wasn't loading last night but I guess its good now.
