### ISSUE TITLE
Display track time on timeline hover

### ISSUE THREAD

**Issue by anshumanv** [anshumanv/ongaku#42]

**Comment by markus-willems** [comment]
Hi @anshumanv, I would like to add this feature :) Could you tell me a bit more about this feature? Like, where exactly the track time should be displayed?

**Comment by anshumanv** [comment]
Hey, @markus-willems thanks for showing interest here.
When we hover over the song timeline i.e the line which fills as song proceeds to display the playtime when the mouse is present.
That being said, we are planning to change the whole Audio Player so this issue is to be solved after #192 please look into it if you can help with that.
