### ISSUE TITLE
Volume bar on home page

### ISSUE THREAD

**Issue by Prakash2403** [anshumanv/ongaku#45]
Views @Monal5031 @Anshuman-Verma ??

**Comment by anshumanv** [comment]
Surely that is a necessity, thanks for the suggestion sir :+1:  
Also we can have keycodes like up and down arrow to control volume too.
Would you like to take this @Prakash2403  ?

**Comment by Prakash2403** [comment]
Sorry @Anshuman-Verma , I don't know much `JS`.

**Comment by anshumanv** [comment]
No problem @Prakash2403 , none of us know much actually :laughing: 
Appreciate the suggestion though. I'll assign it to myself in that case.

**Comment by anshumanv** [comment]
Apparently we have attached `Keycodes` to browser window https://github.com/Anshuman-Verma/ongaku#features to control volume and seeking track, I will add a volume bar if need arises.
Hence, closing this now.
