### ISSUE TITLE
Add github link of this repo on website

### ISSUE THREAD

**Issue by Prakash2403** [anshumanv/ongaku#49]
Doing this may attract developers.

**Comment by anshumanv** [comment]
Awesome, we surely need one.
Here's the link of git ribbons that i came accross https://github.com/blog/273-github-ribbons
Up for it @Prakash2403 ?

**Comment by Prakash2403** [comment]
@Anshuman-Verma  I don't know HTML, CSS either 😄

**Comment by Monal5031** [comment]
Can I do this one? @Anshuman-Verma
