### ISSUE TITLE
Feature to show playlist

### ISSUE THREAD

**Issue by aviaryan** [anshumanv/ongaku#79]
An option to show the list of all songs and let users choose a song to play.

**Comment by anshumanv** [comment]
Right, this feature is currently under dev. in #25 by @Monal5031 , though selection of tracks from the displayed list is one great thing we can incorporate !

**Comment by anshumanv** [comment]
Current plan is to have a slider button on top-left, which will slide in the tracks list onto the screen. 
Any suggestions/thoughts on this @aviaryan ?

**Comment by aviaryan** [comment]
No, that is exactly what I had in mind.

**Comment by Monal5031** [comment]
Solution for this was fixed in https://github.com/Monal5031/Js-css-Experimentations/issues/7

**Comment by anshumanv** [comment]
This is ongoing in #183

**Comment by anshumanv** [comment]
Done in #187
